<a href="https://colab.research.google.com/github/MauricioGomez-2520612022/etl-data-pipeline/blob/main/etl_aseguradoras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/MauricioGomez-2520612022/etl-data-pipeline

In [2]:
import pandas as pd

In [3]:
url = "https://raw.githubusercontent.com/MauricioGomez-2520612022/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

In [4]:
df = pd.read_csv(url)
df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [5]:
#Limpieza de datos
aseguradoras = df.copy()

aseguradoras.columns = aseguradoras.columns.str.strip().str.lower()

for col in aseguradoras.select_dtypes(include="object").columns:
    aseguradoras[col] = aseguradoras[col].astype(str).str.strip()

aseguradoras = aseguradoras.replace(r'^\s*$', pd.NA, regex=True)

aseguradoras['id_aseguradora'] = pd.to_numeric(
    aseguradoras['id_aseguradora'],
    errors='coerce'
)

aseguradoras['nombre'] = aseguradoras['nombre'].str.title()
aseguradoras['pais'] = aseguradoras['pais'].str.title()
aseguradoras['rating_riesgo'] = aseguradoras['rating_riesgo'].str.title()

aseguradoras = aseguradoras.drop_duplicates()

In [6]:
#Separacion de validos y rechazados
validos = aseguradoras[
    aseguradoras['id_aseguradora'].notna() &
    aseguradoras['nombre'].notna()
].copy()

rechazados = aseguradoras[
    aseguradoras['id_aseguradora'].isna() |
    aseguradoras['nombre'].isna()
].copy()

In [7]:
#El motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['id_aseguradora']):
        motivos.append("id_aseguradora_vacio")

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [8]:
#Exportar datos
validos.to_csv("aseguradoras_curated.csv", index=False)
rechazados.to_csv("aseguradoras_rejects.csv", index=False)

In [9]:
#Conexion con la BD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:zISc0BFvmmfQ1u43SmeRq5XohVMo55Mn@dpg-d6qu5rh5pdvs73bhfph0-a.oregon-postgres.render.com/etl_seguros_1rr3"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 41.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [11]:
#Cargar tablas a la BD
validos.to_sql(
    'aseguradoras_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'aseguradoras_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [12]:
#Validar datos
pd.read_sql(
    "SELECT * FROM aseguradoras_curated LIMIT 10",
    engine
)

   id_aseguradora          nombre         pais rating_riesgo
0               1   Aseguradora 1   Costa Rica          Alto
1               2   Aseguradora 2  El Salvador          Bajo
2               3   Aseguradora 3  El Salvador           Nan
3               4   Aseguradora 4   Costa Rica         Medio
4               5   Aseguradora 5   Elsalvador             B
5               6   Aseguradora 6          Nan         Medio
6               7   Aseguradora 7    Guatemala          Alto
7               8   Aseguradora 8       Panamá          Bajo
8               9   Aseguradora 9          Nan          Bajo
9              10  Aseguradora 10       Panamá           Nan